// Code generated by coz. DO NOT EDIT.
/**
 * Process manager for the-framework
 * @module the-ps
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const ThePS_ = require('./ThePS')
const acquire_ = require('./acquire')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ThePS = _d(ThePS_)
exports.acquire = _d(acquire_)
exports.create = _d(create_)

module.exports = _d(default__)
