// Code generated by coz. DO NOT EDIT.
/**
 * Process manager for the-framework
 * @module the-ps
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get ThePS () { return _d(require('./ThePS')) },
  get acquire () { return _d(require('./acquire')) },
  get create () { return _d(require('./create')) },
  get default () { return _d(require('./create')) },
}
