// Code generated by coz. DO NOT EDIT.
/**
 * Process manager for the-framework
 * @module the-ps
 */
'use strict'

import ThePS from './ThePS'
import acquire from './acquire'
import create from './create'

export {
  ThePS,
  acquire,
  create,
}

export default create
